version: '3.1'

services:
  code-demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    environment:
       FLASK_APP: app.py
       FLASK_ENV: development
       FLASK_RUN_PORT: 5000
    working_dir: /app/src
    volumes:
      - .:/app
    entrypoint: ['flask', 'run','-h', "0.0.0.0"]
    tty: true

