version: '3.1'

services:
  code-demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    env_file: ./envs/dev.env
    environment:
       FLASK_APP: app.py
       FLASK_ENV: development
       FLASK_RUN_PORT: 5000
    working_dir: /app/src
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    entrypoint: /app/scripts/docker-entry.sh
    tty: true

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: note
      MYSQL_DATABASE: note
      MYSQL_PASSWORD: note-pass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: always
